// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by python/export_model.py.
// Generated 2026-07-17T04:19:56.007567
// ROM read timing: COMBINATIONAL, zero additional latency
// (Phase 3 frozen decision, PHASE3_NOTES.md item 1). hidden_layer.v
// and output_layer.v drive addr and consume dout in the same cycle --
// do not change this to a registered read without also re-pipelining
// the address generation in both layer modules by one cycle.

module output_bias_rom (
    input  wire [0:0] addr,
    output wire [15:0] dout
);

    reg [15:0] mem [0:1];

    initial begin
        mem[0] = 16'd64811; // signed value = -725
        mem[1] = 16'd725; // signed value = 725
    end

    // Combinational read (zero-latency) -- see note above.
    assign dout = mem[addr];

endmodule
