// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by python/export_model.py.
// Generated 2026-07-17T04:19:56.006738
// ROM read timing: COMBINATIONAL, zero additional latency
// (Phase 3 frozen decision, PHASE3_NOTES.md item 1). hidden_layer.v
// and output_layer.v drive addr and consume dout in the same cycle --
// do not change this to a registered read without also re-pipelining
// the address generation in both layer modules by one cycle.

module hidden_bias_rom (
    input  wire [2:0] addr,
    output wire [15:0] dout
);

    reg [15:0] mem [0:7];

    initial begin
        mem[0] = 16'd65522; // signed value = -14
        mem[1] = 16'd65007; // signed value = -529
        mem[2] = 16'd1; // signed value = 1
        mem[3] = 16'd163; // signed value = 163
        mem[4] = 16'd64850; // signed value = -686
        mem[5] = 16'd275; // signed value = 275
        mem[6] = 16'd108; // signed value = 108
        mem[7] = 16'd64983; // signed value = -553
    end

    // Combinational read (zero-latency) -- see note above.
    assign dout = mem[addr];

endmodule
