// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by python/export_model.py.
// Generated 2026-07-17T04:19:56.006276
// ROM read timing: COMBINATIONAL, zero additional latency
// (Phase 3 frozen decision, PHASE3_NOTES.md item 1). hidden_layer.v
// and output_layer.v drive addr and consume dout in the same cycle --
// do not change this to a registered read without also re-pipelining
// the address generation in both layer modules by one cycle.

module hidden_weight_rom (
    input  wire [4:0] addr,
    output wire [15:0] dout
);

    reg [15:0] mem [0:31];

    initial begin
        mem[0] = 16'd42; // signed value = 42
        mem[1] = 16'd65533; // signed value = -3
        mem[2] = 16'd58; // signed value = 58
        mem[3] = 16'd65475; // signed value = -61
        mem[4] = 16'd64779; // signed value = -757
        mem[5] = 16'd65223; // signed value = -313
        mem[6] = 16'd65457; // signed value = -79
        mem[7] = 16'd5; // signed value = 5
        mem[8] = 16'd113; // signed value = 113
        mem[9] = 16'd131; // signed value = 131
        mem[10] = 16'd129; // signed value = 129
        mem[11] = 16'd77; // signed value = 77
        mem[12] = 16'd189; // signed value = 189
        mem[13] = 16'd134; // signed value = 134
        mem[14] = 16'd65520; // signed value = -16
        mem[15] = 16'd78; // signed value = 78
        mem[16] = 16'd64326; // signed value = -1210
        mem[17] = 16'd65225; // signed value = -311
        mem[18] = 16'd1; // signed value = 1
        mem[19] = 16'd22; // signed value = 22
        mem[20] = 16'd65440; // signed value = -96
        mem[21] = 16'd173; // signed value = 173
        mem[22] = 16'd65377; // signed value = -159
        mem[23] = 16'd52; // signed value = 52
        mem[24] = 16'd36; // signed value = 36
        mem[25] = 16'd76; // signed value = 76
        mem[26] = 16'd182; // signed value = 182
        mem[27] = 16'd358; // signed value = 358
        mem[28] = 16'd64713; // signed value = -823
        mem[29] = 16'd65142; // signed value = -394
        mem[30] = 16'd28; // signed value = 28
        mem[31] = 16'd65517; // signed value = -19
    end

    // Combinational read (zero-latency) -- see note above.
    assign dout = mem[addr];

endmodule
