// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.
// Generated by python/export_model.py.
// Generated 2026-07-17T04:19:56.007206
// ROM read timing: COMBINATIONAL, zero additional latency
// (Phase 3 frozen decision, PHASE3_NOTES.md item 1). hidden_layer.v
// and output_layer.v drive addr and consume dout in the same cycle --
// do not change this to a registered read without also re-pipelining
// the address generation in both layer modules by one cycle.

module output_weight_rom (
    input  wire [3:0] addr,
    output wire [15:0] dout
);

    reg [15:0] mem [0:15];

    initial begin
        mem[0] = 16'd65474; // signed value = -62
        mem[1] = 16'd730; // signed value = 730
        mem[2] = 16'd65460; // signed value = -76
        mem[3] = 16'd65361; // signed value = -175
        mem[4] = 16'd1016; // signed value = 1016
        mem[5] = 16'd65353; // signed value = -183
        mem[6] = 16'd65424; // signed value = -112
        mem[7] = 16'd774; // signed value = 774
        mem[8] = 16'd65456; // signed value = -80
        mem[9] = 16'd64992; // signed value = -544
        mem[10] = 16'd65510; // signed value = -26
        mem[11] = 16'd157; // signed value = 157
        mem[12] = 16'd64657; // signed value = -879
        mem[13] = 16'd136; // signed value = 136
        mem[14] = 16'd147; // signed value = 147
        mem[15] = 16'd64879; // signed value = -657
    end

    // Combinational read (zero-latency) -- see note above.
    assign dout = mem[addr];

endmodule
