//==============================================================================
// pynq_z2_top.v
// TinyRISC-TinyML -- physical top-level for the PYNQ-Z2 board.
//
// Port names below MUST match constraints/pynq_z2.xdc exactly (sysclk,
// btn0, led[3:0], uart_tx, uart_rx) -- these are the only signals
// actually constrained to physical pins.
//
// Wraps soc_top.v (Phase 6, unchanged) with:
//   1. A Clocking Wizard IP (clk_wiz_0, generated by vivado/scripts/
//      create_project.tcl) dividing the board's 125 MHz oscillator down
//      to a clean 50 MHz -- matching software's SYSTEM_CLOCK_HZ
//      assumption exactly, so no firmware recompilation is needed.
//   2. A standard 2-FF reset synchronizer: asynchronous assert (button
//      press OR clock not yet locked forces reset immediately),
//      synchronous deassert (reset is only released on a clean clk_50mhz
//      edge, avoiding metastability). The system stays in reset until
//      the Clocking Wizard reports `locked`, so soc_top never sees a
//      glitchy or not-yet-stable clock.
//
// FIRMWARE_HEX_FILE: passed straight through to soc_top -- build this
// project TWICE (once per firmware image) via create_project.tcl's
// FIRMWARE argument, producing two separate bitstreams for the Version 1
// vs. Version 2 hardware comparison (AC-02), exactly mirroring the two
// firmware images from Phase 5.
//==============================================================================
`timescale 1ns / 1ps

module pynq_z2_top #(
    parameter FIRMWARE_HEX_FILE = "firmware_hw.hex"
) (
    input  wire sysclk,   // 125 MHz board oscillator (pin H16, see XDC)
    input  wire btn0,     // active-high push button, used as reset

    output wire [3:0] led,
    output wire uart_tx,
    input  wire uart_rx
);

    wire clk_50mhz;
    wire clk_locked;

    clk_wiz_0 u_clk_wiz (
        .clk_in1  (sysclk),
        .reset    (1'b0),      // MMCM's own reset -- unused, power-on-reset is sufficient
        .clk_out1 (clk_50mhz),
        .locked   (clk_locked)
    );

    // Asynchronous assert, synchronous deassert -- standard reset
    // synchronizer pattern. Held in reset if the button is pressed OR
    // the Clocking Wizard has not yet locked.
    wire raw_resetn = (~btn0) & clk_locked;

    reg [1:0] resetn_sync;
    always @(posedge clk_50mhz or negedge raw_resetn) begin
        if (!raw_resetn)
            resetn_sync <= 2'b00;
        else
            resetn_sync <= {resetn_sync[0], 1'b1};
    end

    wire resetn = resetn_sync[1];

    soc_top #(
        .FIRMWARE_HEX_FILE (FIRMWARE_HEX_FILE)
    ) u_soc (
        .clk     (clk_50mhz),
        .resetn  (resetn),
        .uart_tx (uart_tx),
        .uart_rx (uart_rx),
        .led     (led)
    );

endmodule
