"""
export_model.py
----------------
THE ONLY SCRIPT ALLOWED TO WRITE INTO generated/.

Takes the quantized (Q8.8) model and emits two bit-for-bit-matched
artifact sets from one source of truth:

  generated/software/weights.h            (C arrays for software_nn.c)
  generated/software/test_vectors.h       (C arrays, shared test inputs)
  generated/software/expected_outputs.h   (C arrays, golden reference)

  generated/hardware/hidden_weight_rom.v
  generated/hardware/hidden_bias_rom.v
  generated/hardware/output_weight_rom.v
  generated/hardware/output_bias_rom.v

Addressing convention (matches HDS hidden_layer spec exactly, and is
applied consistently to the output layer too):
    weight_addr = neuron_idx * fan_in + input_idx
  hidden layer: fan_in = NUM_INPUTS (4)  -> addr range 0..31 (5 bits)
  output layer: fan_in = NUM_HIDDEN (8)  -> addr range 0..15 (4 bits)
  bias_addr = neuron_idx (3 bits for hidden, 1 bit for output)

Usage:
    python3 export_model.py
Reads:  python/artifacts/model_quant.npz, dataset/processed/features.npz
Writes: generated/software/*.h, generated/hardware/*.v
"""

import datetime
import numpy as np

import config
import utils
import quantize  # reuse quantize_forward() as the golden-reference forward pass


GENERATED_HEADER_NOTICE = (
    "// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.\n"
    "// Generated by python/export_model.py. Any manual edit will be silently\n"
    "// overwritten on the next export and will desynchronize software and\n"
    "// hardware representations of the model.\n"
)


def flatten_hidden_weights(W1_q):
    """W1_q: (NUM_INPUTS, NUM_HIDDEN) int array -> flat list length 32,
    ordered addr = neuron_idx * NUM_INPUTS + input_idx."""
    flat = np.zeros(config.NUM_HIDDEN * config.NUM_INPUTS, dtype=np.int64)
    for neuron_idx in range(config.NUM_HIDDEN):
        for input_idx in range(config.NUM_INPUTS):
            addr = neuron_idx * config.NUM_INPUTS + input_idx
            flat[addr] = W1_q[input_idx, neuron_idx]
    return flat


def flatten_output_weights(W2_q):
    """W2_q: (NUM_HIDDEN, NUM_OUTPUTS) int array -> flat list length 16,
    ordered addr = class_idx * NUM_HIDDEN + hidden_idx."""
    flat = np.zeros(config.NUM_OUTPUTS * config.NUM_HIDDEN, dtype=np.int64)
    for class_idx in range(config.NUM_OUTPUTS):
        for hidden_idx in range(config.NUM_HIDDEN):
            addr = class_idx * config.NUM_HIDDEN + hidden_idx
            flat[addr] = W2_q[hidden_idx, class_idx]
    return flat


# ---------------------------------------------------------------------
# C header generation (generated/software/)
# ---------------------------------------------------------------------

def format_c_int16_array(name, values):
    values = [int(v) for v in values]
    body = ", ".join(str(v) for v in values)
    return f"static const int16_t {name}[{len(values)}] = {{ {body} }};\n"


def write_weights_h(params_q):
    hidden_w_flat = flatten_hidden_weights(params_q["W1_q"])
    output_w_flat = flatten_output_weights(params_q["W2_q"])

    lines = [
        GENERATED_HEADER_NOTICE,
        f"// Generated {datetime.datetime.now().isoformat()}",
        "#ifndef WEIGHTS_H",
        "#define WEIGHTS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define NUM_INPUTS  {config.NUM_INPUTS}",
        f"#define NUM_HIDDEN  {config.NUM_HIDDEN}",
        f"#define NUM_OUTPUTS {config.NUM_OUTPUTS}",
        "",
        "// Addressing: hidden_weights[neuron_idx * NUM_INPUTS + input_idx]",
        format_c_int16_array("hidden_weights", hidden_w_flat),
        "// Addressing: hidden_biases[neuron_idx]",
        format_c_int16_array("hidden_biases", params_q["b1_q"]),
        "// Addressing: output_weights[class_idx * NUM_HIDDEN + hidden_idx]",
        format_c_int16_array("output_weights", output_w_flat),
        "// Addressing: output_biases[class_idx]",
        format_c_int16_array("output_biases", params_q["b2_q"]),
        "",
        "#endif // WEIGHTS_H",
    ]
    utils.ensure_dir(config.WEIGHTS_H_PATH)
    with open(config.WEIGHTS_H_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    utils.log(f"wrote {config.WEIGHTS_H_PATH}")


def write_test_vectors_and_expected_outputs(params_q):
    data = utils.load_npz(config.PROCESSED_FEATURES_PATH)
    X_test, y_test = data["test_features"], data["test_labels"]

    n = min(config.NUM_EXPORTED_TEST_VECTORS, X_test.shape[0])
    X_export = X_test[:n]
    y_export = y_test[:n]

    X_export_q = utils.float_to_q88(X_export)  # (n, 4) int, Q8.8

    _, _, preds_q = quantize.quantize_forward(params_q, X_export)

    agreement = float((preds_q == y_export).mean())
    utils.log(f"export set: {n} vectors, quantized-model vs. true-label "
              f"agreement = {agreement:.3f}")

    # --- test_vectors.h ---
    tv_lines = [
        GENERATED_HEADER_NOTICE,
        "#ifndef TEST_VECTORS_H",
        "#define TEST_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define NUM_TEST_VECTORS {n}",
        "",
        "// Each row: [RMS, Peak, Kurtosis, CrestFactor], Q8.8 fixed point.",
        "// Order matches FEATURE0..FEATURE3 in accelerator_registers.",
        f"static const int16_t test_vectors[NUM_TEST_VECTORS][{config.NUM_FEATURES}] = {{",
    ]
    for row in X_export_q:
        tv_lines.append("    { " + ", ".join(str(int(v)) for v in row) + " },")
    tv_lines += ["};", "", "#endif // TEST_VECTORS_H"]

    utils.ensure_dir(config.TEST_VECTORS_H_PATH)
    with open(config.TEST_VECTORS_H_PATH, "w") as f:
        f.write("\n".join(tv_lines) + "\n")
    utils.log(f"wrote {config.TEST_VECTORS_H_PATH}")

    # --- expected_outputs.h ---
    eo_lines = [
        GENERATED_HEADER_NOTICE,
        "#ifndef EXPECTED_OUTPUTS_H",
        "#define EXPECTED_OUTPUTS_H",
        "",
        "#include <stdint.h>",
        "",
        "// Golden-reference predicted class per test vector (0=Normal, 1=Fault),",
        "// computed from the Q8.8 quantized model -- this is what both",
        "// software_nn.c and the RTL accelerator must reproduce.",
        f"static const uint8_t expected_outputs[NUM_TEST_VECTORS] = {{ "
        + ", ".join(str(int(p)) for p in preds_q) + " };",
        "",
        "#endif // EXPECTED_OUTPUTS_H",
    ]
    utils.ensure_dir(config.EXPECTED_OUTPUTS_H_PATH)
    with open(config.EXPECTED_OUTPUTS_H_PATH, "w") as f:
        f.write("\n".join(eo_lines) + "\n")
    utils.log(f"wrote {config.EXPECTED_OUTPUTS_H_PATH}")


# ---------------------------------------------------------------------
# Verilog ROM generation (generated/hardware/)
# ---------------------------------------------------------------------

def write_verilog_rom(path, module_name, addr_width, data_width, values):
    values = [int(v) for v in values]
    depth = len(values)

    lines = [
        "// AUTO-GENERATED FILE -- DO NOT EDIT BY HAND.",
        "// Generated by python/export_model.py.",
        f"// Generated {datetime.datetime.now().isoformat()}",
        "// ROM read timing: COMBINATIONAL, zero additional latency",
        "// (Phase 3 frozen decision, PHASE3_NOTES.md item 1). hidden_layer.v",
        "// and output_layer.v drive addr and consume dout in the same cycle --",
        "// do not change this to a registered read without also re-pipelining",
        "// the address generation in both layer modules by one cycle.",
        "",
        f"module {module_name} (",
        f"    input  wire [{addr_width-1}:0] addr,",
        f"    output wire [{data_width-1}:0] dout",
        ");",
        "",
        f"    reg [{data_width-1}:0] mem [0:{depth-1}];",
        "",
        "    initial begin",
    ]
    for i, v in enumerate(values):
        # Store as unsigned bit pattern of the signed Q8.8 value.
        unsigned_bits = v & ((1 << data_width) - 1)
        lines.append(f"        mem[{i}] = {data_width}'d{unsigned_bits}; "
                      f"// signed value = {v}")
    lines += [
        "    end",
        "",
        "    // Combinational read (zero-latency) -- see note above.",
        "    assign dout = mem[addr];",
        "",
        "endmodule",
    ]

    utils.ensure_dir(path)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    utils.log(f"wrote {path} ({depth} entries, addr_width={addr_width})")


def write_hardware_roms(params_q):
    hidden_w_flat = flatten_hidden_weights(params_q["W1_q"])
    output_w_flat = flatten_output_weights(params_q["W2_q"])

    write_verilog_rom(
        config.HIDDEN_WEIGHT_ROM_PATH, "hidden_weight_rom",
        addr_width=5, data_width=16, values=hidden_w_flat,
    )
    write_verilog_rom(
        config.HIDDEN_BIAS_ROM_PATH, "hidden_bias_rom",
        addr_width=3, data_width=16, values=params_q["b1_q"],
    )
    write_verilog_rom(
        config.OUTPUT_WEIGHT_ROM_PATH, "output_weight_rom",
        addr_width=4, data_width=16, values=output_w_flat,
    )
    write_verilog_rom(
        config.OUTPUT_BIAS_ROM_PATH, "output_bias_rom",
        addr_width=1, data_width=16, values=params_q["b2_q"],
    )


def export_all():
    params_q = {
        "W1_q": utils.load_npz(config.QUANT_MODEL_PATH)["W1_q"],
        "b1_q": utils.load_npz(config.QUANT_MODEL_PATH)["b1_q"],
        "W2_q": utils.load_npz(config.QUANT_MODEL_PATH)["W2_q"],
        "b2_q": utils.load_npz(config.QUANT_MODEL_PATH)["b2_q"],
    }

    write_weights_h(params_q)
    write_test_vectors_and_expected_outputs(params_q)
    write_hardware_roms(params_q)

    utils.log("export_model.py complete -- generated/ is now up to date.")


if __name__ == "__main__":
    export_all()
